markdown: kramdown
kramdown:
  math_engine: mathjax
# markdown: redcarpet
highlighter: rouge
permalink: blog/:year/:month/:day/:title.html
# permalink: /:categories/:title.html
# permalink: pretty
paginate: 6
# pygments: true
paginate_path: page/:num
gems: ['jekyll-paginate','kramdown']

# heroku
# exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

blog:
    name: cuizixin                                                # 博客名称
    description: 取乎其上，脚踏实地                                      # 博客描述
    title: czx229'blog                                                # 网页标题
    url:  www.cuizixin.top                                               # 博客地址
    duoshuo: cxy229  # 多说ID
    tongji:  3ae657959e8611568ba7987f47b5b6db # 百度统计ID
    qiniu: http://7xqql4.com1.z0.glb.clouddn.com/        # 七牛云地址
author:
    name: czx229 # 作者名称
    email: cxyxs229@gmail.com # 邮箱地址
    weibo: # 微博地址
    github: https://github.com/cxy229 # GitHub地址
    logo: http://7xqql4.com1.z0.glb.clouddn.com/ico.jpg # logo地址
  #  douban:
  #      name: cxy229                                            # 豆瓣地址名称
  #      key:                                             # 豆瓣API Key
# scp -r _site/ git@115.28.237.42:/home/git/web/myblog
